# Compiler is homebrew's gcc-5 (GCC 5.2.0)
CC	= gcc-5
# Compilation flags
#  -g		debugging metadata added to executable
#  -Wall	most warnings are displayed
#  -Wpedantic	warn if style is bad
#  -std=c11	use the modern C11 standard
CFLAGS 	= -g -Wall -Wpedantic -std=c11 -O2
# Directories containing header files other than /usr/include
INCLUDES=
# Library paths in addition to /usr/lib
LFLAGS	=
# Any libraries to include
LIBS 	=
# Source .c files
SRCS 	= lineread.c mips_read.c
# Object files to compile
OBJS 	= $(SRCS:.c=.o)
# Main executable file
MAIN 	= lineread

.PHONY: depend clean

all:	$(MAIN)

$(MAIN): $(OBJS)
	$(CC) $(CFLAGS) $(INCLUDES) -o $(MAIN) $(OBJS) $(LFLAGS) $(LIBS)

.c.o:
	$(CC) $(CFLAGS) $(INCLUDES) -c $< -o $@

clean:
	$(RM) *.o *~ $(MAIN)

depend: $(SRCS)
	makedepend $^

#
# DO NOT DELETE

lineread.o: /usr/include/stdio.h /usr/include/sys/cdefs.h
lineread.o: /usr/include/sys/_symbol_aliasing.h
lineread.o: /usr/include/sys/_posix_availability.h
lineread.o: /usr/include/Availability.h /usr/include/AvailabilityInternal.h
lineread.o: /usr/include/_types.h /usr/include/sys/_types.h
lineread.o: /usr/include/machine/_types.h /usr/include/i386/_types.h
lineread.o: /usr/include/sys/_pthread/_pthread_types.h
lineread.o: /usr/include/sys/_types/_va_list.h
lineread.o: /usr/include/sys/_types/_size_t.h /usr/include/sys/_types/_null.h
lineread.o: /usr/include/sys/stdio.h /usr/include/sys/_types/_off_t.h
lineread.o: /usr/include/sys/_types/_ssize_t.h /usr/include/secure/_stdio.h
lineread.o: /usr/include/secure/_common.h /usr/include/stdlib.h
lineread.o: /usr/include/sys/wait.h /usr/include/sys/_types/_pid_t.h
lineread.o: /usr/include/sys/_types/_id_t.h /usr/include/sys/signal.h
lineread.o: /usr/include/sys/appleapiopts.h /usr/include/machine/signal.h
lineread.o: /usr/include/i386/signal.h /usr/include/machine/_mcontext.h
lineread.o: /usr/include/i386/_mcontext.h /usr/include/mach/i386/_structs.h
lineread.o: /usr/include/sys/_pthread/_pthread_attr_t.h
lineread.o: /usr/include/sys/_types/_sigaltstack.h
lineread.o: /usr/include/sys/_types/_ucontext.h
lineread.o: /usr/include/sys/_types/_sigset_t.h
lineread.o: /usr/include/sys/_types/_uid_t.h /usr/include/sys/resource.h
lineread.o: /usr/include/stdint.h /usr/include/sys/_types/_int8_t.h
lineread.o: /usr/include/sys/_types/_int16_t.h
lineread.o: /usr/include/sys/_types/_int32_t.h
lineread.o: /usr/include/sys/_types/_int64_t.h /usr/include/_types/_uint8_t.h
lineread.o: /usr/include/_types/_uint16_t.h /usr/include/_types/_uint32_t.h
lineread.o: /usr/include/_types/_uint64_t.h
lineread.o: /usr/include/sys/_types/_intptr_t.h
lineread.o: /usr/include/sys/_types/_uintptr_t.h
lineread.o: /usr/include/_types/_intmax_t.h /usr/include/_types/_uintmax_t.h
lineread.o: /usr/include/sys/_types/_timeval.h /usr/include/machine/endian.h
lineread.o: /usr/include/i386/endian.h /usr/include/sys/_endian.h
lineread.o: /usr/include/libkern/_OSByteOrder.h
lineread.o: /usr/include/libkern/i386/_OSByteOrder.h /usr/include/alloca.h
lineread.o: /usr/include/sys/_types/_ct_rune_t.h
lineread.o: /usr/include/sys/_types/_rune_t.h
lineread.o: /usr/include/sys/_types/_wchar_t.h /usr/include/machine/types.h
lineread.o: /usr/include/i386/types.h /usr/include/sys/_types/_dev_t.h
lineread.o: /usr/include/sys/_types/_mode_t.h mips_read.h
mips_read.o: /usr/include/stdlib.h /usr/include/Availability.h
mips_read.o: /usr/include/AvailabilityInternal.h /usr/include/_types.h
mips_read.o: /usr/include/sys/_types.h /usr/include/sys/cdefs.h
mips_read.o: /usr/include/sys/_symbol_aliasing.h
mips_read.o: /usr/include/sys/_posix_availability.h
mips_read.o: /usr/include/machine/_types.h /usr/include/i386/_types.h
mips_read.o: /usr/include/sys/_pthread/_pthread_types.h
mips_read.o: /usr/include/sys/wait.h /usr/include/sys/_types/_pid_t.h
mips_read.o: /usr/include/sys/_types/_id_t.h /usr/include/sys/signal.h
mips_read.o: /usr/include/sys/appleapiopts.h /usr/include/machine/signal.h
mips_read.o: /usr/include/i386/signal.h /usr/include/machine/_mcontext.h
mips_read.o: /usr/include/i386/_mcontext.h /usr/include/mach/i386/_structs.h
mips_read.o: /usr/include/sys/_pthread/_pthread_attr_t.h
mips_read.o: /usr/include/sys/_types/_sigaltstack.h
mips_read.o: /usr/include/sys/_types/_ucontext.h
mips_read.o: /usr/include/sys/_types/_sigset_t.h
mips_read.o: /usr/include/sys/_types/_size_t.h
mips_read.o: /usr/include/sys/_types/_uid_t.h /usr/include/sys/resource.h
mips_read.o: /usr/include/stdint.h /usr/include/sys/_types/_int8_t.h
mips_read.o: /usr/include/sys/_types/_int16_t.h
mips_read.o: /usr/include/sys/_types/_int32_t.h
mips_read.o: /usr/include/sys/_types/_int64_t.h
mips_read.o: /usr/include/_types/_uint8_t.h /usr/include/_types/_uint16_t.h
mips_read.o: /usr/include/_types/_uint32_t.h /usr/include/_types/_uint64_t.h
mips_read.o: /usr/include/sys/_types/_intptr_t.h
mips_read.o: /usr/include/sys/_types/_uintptr_t.h
mips_read.o: /usr/include/_types/_intmax_t.h /usr/include/_types/_uintmax_t.h
mips_read.o: /usr/include/sys/_types/_timeval.h /usr/include/machine/endian.h
mips_read.o: /usr/include/i386/endian.h /usr/include/sys/_endian.h
mips_read.o: /usr/include/libkern/_OSByteOrder.h
mips_read.o: /usr/include/libkern/i386/_OSByteOrder.h /usr/include/alloca.h
mips_read.o: /usr/include/sys/_types/_ct_rune_t.h
mips_read.o: /usr/include/sys/_types/_rune_t.h
mips_read.o: /usr/include/sys/_types/_wchar_t.h
mips_read.o: /usr/include/sys/_types/_null.h /usr/include/machine/types.h
mips_read.o: /usr/include/i386/types.h /usr/include/sys/_types/_dev_t.h
mips_read.o: /usr/include/sys/_types/_mode_t.h /usr/include/stdio.h
mips_read.o: /usr/include/sys/_types/_va_list.h /usr/include/sys/stdio.h
mips_read.o: /usr/include/sys/_types/_off_t.h
mips_read.o: /usr/include/sys/_types/_ssize_t.h /usr/include/secure/_stdio.h
mips_read.o: /usr/include/secure/_common.h mips_read.h
